//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Encheres = new HashSet<Enchere>();
            this.Images = new HashSet<Image>();
            this.Messages = new HashSet<Message>();
            this.Encherisseurs = new HashSet<Encherisseur>();
        }
    
        public int IdArticle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateMiseEnVente { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
        public Nullable<double> PrixMiseEnVente { get; set; }
        public int IdCategorie { get; set; }
        public Nullable<double> PrixReserve { get; set; }
        public string PseudoVendeur { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Vendeur Vendeur { get; set; }
        public virtual ICollection<Enchere> Encheres { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Encherisseur> Encherisseurs { get; set; }
    }
}
