//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Articles = new HashSet<Article>();
            this.Categorie1 = new HashSet<Categorie>();
        }
    
        public int IdCategorie { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> IdCategorieAppartenance { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Categorie> Categorie1 { get; set; }
        public virtual Categorie Categorie2 { get; set; }
    }
}
