//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db2014IbeilleEntities : DbContext
    {
        public Db2014IbeilleEntities()
            : base("name=Db2014IbeilleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Enchere> Encheres { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Inscrit> Inscrits { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    }
}
