//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encherisseur : Inscrit
    {
        public Encherisseur()
        {
            this.Encheres = new HashSet<Enchere>();
            this.Messages = new HashSet<Message>();
            this.Articles = new HashSet<Article>();
        }
    
    
        public virtual ICollection<Enchere> Encheres { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
