//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enchere
    {
        public int idEnchere { get; set; }
        public double Montant { get; set; }
        public Nullable<System.DateTime> DateEnchere { get; set; }
        public int IdArticle { get; set; }
        public string PseudoEncherisseur { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Encherisseur Encherisseur { get; set; }
    }
}
