//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int idImage { get; set; }
        public byte[] imageSource { get; set; }
        public byte[] Image1 { get; set; }
        public Nullable<int> IdArticle { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
