//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Message1 = new HashSet<Message>();
        }
    
        public int idMessage { get; set; }
        public string contenu { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public int idArticle { get; set; }
        public string PseudoVendeur { get; set; }
        public string PseudoEncherisseur { get; set; }
        public Nullable<int> idQuestion { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Encherisseur Encherisseur { get; set; }
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
        public virtual Vendeur Vendeur { get; set; }
    }
}
