//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lbeille.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendeur : Inscrit
    {
        public Vendeur()
        {
            this.Articles = new HashSet<Article>();
            this.Messages = new HashSet<Message>();
        }
    
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
